name: Setup Maven
description: |
  Maven wrapper to abstract defaults for setting maven up
inputs:
  java-version:
    description: Java version to be used
    required: false
    default: '21'
  distribution:
    description: Java distribution to be used
    required: false
    default: 'temurin'
  maven-version:
    description: Maven version to be used
    required: false
    default: '3.8.6'
  secrets:
    description: JSON wrapped secrets for easier secret passing
    required: true
runs:
  using: composite
  steps:
  - name: Setup Maven Action
    uses: s4u/setup-maven-action@2f53a7669c7543a045d0bb6c92436df0c5a726f8 # v1.14.0
    with:
      java-version: ${{ inputs.java-version }}
      java-distribution: ${{ inputs.distribution }}
      maven-version: ${{ inputs.maven-version }}
