name: Setup Maven
description: |
  Maven wrapper to abstract defaults for setting maven up
inputs:
  java-version:
    description: Java version to be used
    required: false
    default: '21'
  distribution:
    description: Java distribution to be used
    required: false
    default: 'temurin'
  maven-version:
    description: Maven version to be used
    required: false
    default: '3.8.6'
  secrets:
    description: JSON wrapped secrets for easier secret passing
    required: true
runs:
  using: composite
  steps:
  - name: 'Create settings.xml'
    uses: s4u/maven-settings-action@7802f6aec16c9098b4798ad1f1d8ac75198194bd # v3.0.0
    with:
      githubServer: false
      servers: |
        [{
          "id": "camunda-nexus",
          "username": "${{ steps.secrets.outputs.NEXUS_USERNAME }}",
          "password": "${{ steps.secrets.outputs.NEXUS_PASSWORD }}"
        }]
      mirrors: '[{"url": "https://repository.nexus.camunda.cloud/content/groups/internal/", "id": "camunda-nexus", "mirrorOf": "*", "name": "camunda Nexus"}]'
