name: Assign labeled issues to projects
on:
  issues:
    types:
      - labeled
jobs:
  add-to-projects:
    strategy:
      matrix:
        teams:
          [
            { name: "Operate", label: "component/operate", projectId: "24" },
            { name: "Tasklist", label: "component/tasklist", projectId: "41" },
            { name: "Optimize", label: "component/optimize", projectId: "101" },
          ]
    name: Add ${{ matrix.teams.name }} issue to project if relevant component label added
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add labeled issue to project
        if: ${{ github.event.label.name == matrix.teams.label }}
        uses: ./.github/actions/add-issue-to-project
        with:
          projectId: ${{ matrix.teams.projectId }}
          issueNumber: ${{ github.event.issue.number }}
          githubToken: ${{ secrets.GH_PROJECT_AUTOMATION_TOKEN }}
