name: Operate Frontend
on:
  push:
    branches:
      - main
      - stable/operate-8.5
    paths:
      - 'operate/client/**'
      - '!.github/workflows/zeebe-*'
      - '!dist/**'
      - '!zeebe/**'
      - '!spring-boot-starter-camunda-sdk/**'
  pull_request:
    paths:
      - 'operate/client/**'
      - '!.github/workflows/zeebe-*'
      - '!dist/**'
      - '!zeebe/**'
      - '!spring-boot-starter-camunda-sdk/**'

jobs:
  linting-and-testing:
    name: Linting & Testing
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: operate/client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: operate/client/yarn.lock
      - run: yarn install --frozen-lockfile
        name: Install dependencies
      - run: yarn ts-check
        name: Type checks
      - run: yarn eslint
        name: ESLint
      - run: yarn test:ci
        name: Unit & Integration tests
