name: Operate Check project versions

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch name to check the versions in."
        type: string
        required: true
      zeebeVersion:
        description: "Released Zeebe version to compare to the current Zeebe version in code."
        type: string
        required: true
      identityVersion:
        description: "Released Identity version to compare to the current Identity version in code."
        type: string
        required: true

jobs:
  check_project_versions:
    name: "'${{ inputs.branch }}' branch"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout '${{ inputs.branch }}' branch"
        uses: actions/checkout@v4
        with:
          ref: refs/heads/${{ inputs.branch }}
          fetch-depth: 0  
            
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.6

      - name: Check versions
        env:
          EXPECTED_ZEEBE_VERSION: ${{ inputs.zeebeVersion }}
          EXPECTED_IDENTITY_VERSION: ${{ inputs.identityVersion }}
          BRANCH_NAME: ${{ inputs.branchName }}
        run: |
          ACTUAL_ZEEBE_VERSION=$(mvn -f operate help:evaluate -Dexpression=version.zeebe -q -DforceStdout)
          ACTUAL_IDENTITY_VERSION=$(mvn -f operate help:evaluate -Dexpression=version.identity -q -DforceStdout)

          if [[ $ACTUAL_ZEEBE_VERSION != $EXPECTED_ZEEBE_VERSION || $ACTUAL_IDENTITY_VERSION != $EXPECTED_IDENTITY_VERSION ]]; then
            echo "Please update Zeebe and Identity versions!"
            echo "Current Zeebe version: $ACTUAL_ZEEBE_VERSION"
            echo "Should be updated to: $EXPECTED_ZEEBE_VERSION"
            echo "Current Identity version: $ACTUAL_IDENTITY_VERSION"
            echo "Should be updated to: $EXPECTED_IDENTITY_VERSION"

            exit 1
          fi


          echo "Zeebe and Identity versions are correct!"
