---
name: Preview Environment Build

on:
  pull_request: {}

# Limit workflow to 1 concurrent run per ref (branch): new commit -> old runs are canceled to save costs
# Exception for main branch: complete builds for every commit needed for confidenence
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}

defaults:
  run:
    # use bash shell by default to ensure pipefail behavior is the default
    # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

jobs:
  build-operare:
    name: Operate Build
    uses: ./.github/workflows/operate-ci-build-reusable.yml
    secrets: inherit
    with:
      branch: ${{ github.head_ref || github.ref_name }}
      previewEnv: true

  build-tasklist:
    name: Tasklist Build
    uses: ./.github/workflows/tasklist-ci-build-reusable.yml
    secrets: inherit
    with:
      branch: ${{ github.head_ref || github.ref_name }}
      previewEnv: true

  build-zeebe:
    name: Zeebe Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      #########################################################################
      # Docker login and image tagging
      - name: Login to Harbor docker registry
        uses: docker/login-action@v3
        with:
          registry: dev.registry.camunda.cloud
          username: ${{ steps.secrets.outputs.NEXUS_USR }}
          password: ${{ steps.secrets.outputs.NEXUS_PSW }}

      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v3.0.0
        if: |
          inputs.secret_vault_address != ''
          && inputs.secret_vault_roleId != ''
          && inputs.secret_vault_secretId != ''
        with:
          url: ${{ inputs.secret_vault_address }}
          method: approle
          roleId: ${{ inputs.secret_vault_roleId }}
          secretId: ${{ inputs.secret_vault_secretId }}
          secrets: |
            secret/data/github.com/organizations/camunda NEXUS_USR;
            secret/data/github.com/organizations/camunda NEXUS_PSW;

      - uses: ./.github/actions/setup-zeebe
        with:
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}

      - uses: ./.github/actions/build-zeebe
        id: build-zeebe
        with:
          maven-extra-args: -T1C -PskipFrontendBuild

      - uses: ./.github/actions/build-platform-docker
        id: build-zeebe-docker
        with:
          repository: dev.registry.camunda.cloud/team-camunda/zeebe
          version: pr-${{ github.sha }}
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: true
          distball: ${{ steps.build-zeebe.outputs.distball }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
          preview-env: true
