name: Test Maven CI
on:
  pull_request:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}

defaults:
  run:
    # use bash shell by default to ensure pipefail behavior is the default
    # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

# set permissions to allow to publish test results
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  docker:
    name: Test Maven CI Optimize Build
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/optimize-ci-build-reusable.yml
    secrets: inherit
    with:
      branch: ${{ github.head_ref }}
  build-optimize:
    if: github.event.pull_request.state != 'closed' && (contains( github.event.label.name, 'deploy-preview') || contains( github.event.pull_request.labels.*.name, 'deploy-preview'))
    name: Optimize Build 2
    uses: ./.github/workflows/optimize-ci-build-reusable.yml
    secrets: inherit
    with:
      branch: ${{ github.head_ref }}
      pushDocker: true
