name: Test Maven CI
on:
  pull_request:

# set permissions to allow to publish test results
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  docker:
    name: Test Maven CI Optimize Build
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/optimize-ci-build-reusable.yml
    secrets: inherit
    with:
      branch: ${{ github.head_ref }}
